#!/usr/bin/env python3

"""Equities domain for Aiera MCP."""

from .tools import (
    find_equities,
    get_sectors_and_subsectors,
    get_equity_summaries,
    get_available_indexes,
    get_index_constituents,
    get_available_watchlists,
    get_watchlist_constituents,
    get_financials,
    get_ratios,
    get_kpis_and_segments,
)
from .models import (
    FindEquitiesArgs,
    GetEquitySummariesArgs,
    GetIndexConstituentsArgs,
    GetWatchlistConstituentsArgs,
    GetAvailableWatchlistsArgs,
    GetAvailableIndexesArgs,
    GetSectorsAndSubsectorsArgs,
    GetFinancialsArgs,
    GetRatiosArgs,
    GetKpisAndSegmentsArgs,
    FindEquitiesResponse,
    GetEquitySummariesResponse,
    GetSectorsSubsectorsResponse,
    GetAvailableIndexesResponse,
    GetIndexConstituentsResponse,
    GetAvailableWatchlistsResponse,
    GetWatchlistConstituentsResponse,
    GetFinancialsResponse,
    GetRatiosResponse,
    GetKpisAndSegmentsResponse,
    EquityItem,
    EquityDetails,
    EquitySummary,
    SectorSubsector,
    IndexItem,
    WatchlistItem,
)

__all__ = [
    # Tools
    "find_equities",
    "get_sectors_and_subsectors",
    "get_equity_summaries",
    "get_available_indexes",
    "get_index_constituents",
    "get_available_watchlists",
    "get_watchlist_constituents",
    "get_financials",
    "get_ratios",
    "get_kpis_and_segments",
    # Parameter models
    "FindEquitiesArgs",
    "GetEquitySummariesArgs",
    "GetIndexConstituentsArgs",
    "GetWatchlistConstituentsArgs",
    "GetAvailableWatchlistsArgs",
    "GetAvailableIndexesArgs",
    "GetSectorsAndSubsectorsArgs",
    "GetFinancialsArgs",
    "GetRatiosArgs",
    "GetKpisAndSegmentsArgs",
    # Response models
    "FindEquitiesResponse",
    "GetEquitySummariesResponse",
    "GetSectorsSubsectorsResponse",
    "GetAvailableIndexesResponse",
    "GetIndexConstituentsResponse",
    "GetAvailableWatchlistsResponse",
    "GetWatchlistConstituentsResponse",
    "GetFinancialsResponse",
    "GetRatiosResponse",
    "GetKpisAndSegmentsResponse",
    # Data models
    "EquityItem",
    "EquityDetails",
    "EquitySummary",
    "SectorSubsector",
    "IndexItem",
    "WatchlistItem",
]
