#!/usr/bin/env python3

"""Research domain for Aiera MCP."""

from .tools import (
    find_research,
    get_research_metadata,
    get_research_metadata_fields,
    get_research,
    get_research_providers,
    get_research_authors,
    get_research_asset_classes,
    get_research_asset_types,
    get_research_subjects,
    get_research_product_focuses,
    get_research_region_types,
    get_research_country_codes,
    report_research_usage,
)
from .models import (
    FindResearchArgs,
    GetResearchArgs,
    GetResearchProvidersArgs,
    GetResearchAuthorsArgs,
    GetResearchAssetClassesArgs,
    GetResearchAssetTypesArgs,
    GetResearchSubjectsArgs,
    GetResearchProductFocusesArgs,
    GetResearchRegionTypesArgs,
    GetResearchCountryCodesArgs,
    ReportResearchUsageArgs,
    GetResearchMetadataArgs,
    GetResearchMetadataFieldsArgs,
    FindResearchResponse,
    GetResearchResponse,
    GetResearchProvidersResponse,
    GetResearchAuthorsResponse,
    GetResearchAssetClassesResponse,
    GetResearchAssetTypesResponse,
    GetResearchSubjectsResponse,
    GetResearchProductFocusesResponse,
    GetResearchRegionTypesResponse,
    GetResearchCountryCodesResponse,
    ReportResearchUsageResponse,
    GetResearchMetadataResponse,
    GetResearchMetadataFieldsResponse,
)

__all__ = [
    # Tools
    "find_research",
    "get_research",
    "get_research_providers",
    "get_research_authors",
    "get_research_asset_classes",
    "get_research_asset_types",
    "get_research_subjects",
    "get_research_product_focuses",
    "get_research_region_types",
    "get_research_country_codes",
    "report_research_usage",
    "get_research_metadata",
    "get_research_metadata_fields",
    # Parameter models
    "FindResearchArgs",
    "GetResearchArgs",
    "GetResearchProvidersArgs",
    "GetResearchAuthorsArgs",
    "GetResearchAssetClassesArgs",
    "GetResearchAssetTypesArgs",
    "GetResearchSubjectsArgs",
    "GetResearchProductFocusesArgs",
    "GetResearchRegionTypesArgs",
    "GetResearchCountryCodesArgs",
    "ReportResearchUsageArgs",
    "GetResearchMetadataArgs",
    "GetResearchMetadataFieldsArgs",
    # Response models
    "FindResearchResponse",
    "GetResearchResponse",
    "GetResearchProvidersResponse",
    "GetResearchAuthorsResponse",
    "GetResearchAssetClassesResponse",
    "GetResearchAssetTypesResponse",
    "GetResearchSubjectsResponse",
    "GetResearchProductFocusesResponse",
    "GetResearchRegionTypesResponse",
    "GetResearchCountryCodesResponse",
    "ReportResearchUsageResponse",
    "GetResearchMetadataResponse",
    "GetResearchMetadataFieldsResponse",
]
