#!/usr/bin/env python3

"""Research domain for Aiera MCP."""

from .tools import (
    find_research,
    get_research,
    get_research_providers,
    find_research_authors,
    find_research_asset_classes,
    find_research_asset_types,
    find_research_subjects,
    find_research_product_focuses,
    find_research_discipline_types,
    find_research_region_types,
    find_research_country_codes,
)
from .models import (
    FindResearchArgs,
    GetResearchArgs,
    GetResearchProvidersArgs,
    FindResearchAuthorsArgs,
    FindResearchAssetClassesArgs,
    FindResearchAssetTypesArgs,
    FindResearchSubjectsArgs,
    FindResearchProductFocusesArgs,
    FindResearchDisciplineTypesArgs,
    FindResearchRegionTypesArgs,
    FindResearchCountryCodesArgs,
    FindResearchResponse,
    GetResearchResponse,
    GetResearchProvidersResponse,
    FindResearchAuthorsResponse,
    FindResearchAssetClassesResponse,
    FindResearchAssetTypesResponse,
    FindResearchSubjectsResponse,
    FindResearchProductFocusesResponse,
    FindResearchDisciplineTypesResponse,
    FindResearchRegionTypesResponse,
    FindResearchCountryCodesResponse,
)

__all__ = [
    # Tools
    "find_research",
    "get_research",
    "get_research_providers",
    "find_research_authors",
    "find_research_asset_classes",
    "find_research_asset_types",
    "find_research_subjects",
    "find_research_product_focuses",
    "find_research_discipline_types",
    "find_research_region_types",
    "find_research_country_codes",
    # Parameter models
    "FindResearchArgs",
    "GetResearchArgs",
    "GetResearchProvidersArgs",
    "FindResearchAuthorsArgs",
    "FindResearchAssetClassesArgs",
    "FindResearchAssetTypesArgs",
    "FindResearchSubjectsArgs",
    "FindResearchProductFocusesArgs",
    "FindResearchDisciplineTypesArgs",
    "FindResearchRegionTypesArgs",
    "FindResearchCountryCodesArgs",
    # Response models
    "FindResearchResponse",
    "GetResearchResponse",
    "GetResearchProvidersResponse",
    "FindResearchAuthorsResponse",
    "FindResearchAssetClassesResponse",
    "FindResearchAssetTypesResponse",
    "FindResearchSubjectsResponse",
    "FindResearchProductFocusesResponse",
    "FindResearchDisciplineTypesResponse",
    "FindResearchRegionTypesResponse",
    "FindResearchCountryCodesResponse",
]
